# -*- coding: utf-8 -*-
"""Updated Save Logic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hp2GBx2uXZPnDKuGJOKKxhYLeCwtrfKj
"""

import win32com.client
import os
import pythoncom

def save_smtp_cache(self):
    """
    Saves the SMTP cache to an Excel file using win32com to ensure
    MSIP/Sensitivity labels are preserved.
    """
    try:
        # 1. First, prepare the data using pandas/dataframe logic as you already do
        # (Assuming self.smtp_cache is a dictionary or similar)
        df = pd.DataFrame(list(self.smtp_cache.items()), columns=['Email', 'SMTP'])

        # Save to a temporary path first if you want to be safe,
        # or just overwrite the existing path.
        temp_path = os.path.abspath(self.smtp_cache_path)

        # 2. Use win32com to handle the Excel Application
        # This ensures the "System" is saving the file, not a library
        pythoncom.CoInitialize() # Required for threading
        excel = win32com.client.Dispatch("Excel.Application")
        excel.Visible = False
        excel.DisplayAlerts = False

        # Check if file exists to decide between Open or Add
        if os.path.exists(temp_path):
            wb = excel.Workbooks.Open(temp_path)
            ws = wb.ActiveSheet
            ws.Cells.ClearContents() # Clear old cache data
        else:
            wb = excel.Workbooks.Add()
            ws = wb.ActiveSheet

        # 3. Efficiently write the headers and data
        ws.Cells(1, 1).Value = "Email"
        ws.Cells(1, 2).Value = "SMTP"

        # Convert dataframe to list of lists for fast writing
        data_to_write = df.values.tolist()
        if data_to_write:
            # Define the range (Start Row, Start Col, End Row, End Col)
            end_row = len(data_to_write) + 1
            ws.Range(ws.Cells(2, 1), ws.Cells(end_row, 2)).Value = data_to_write

        # 4. Save and Close - This is where the MSIP label is maintained/re-applied
        wb.SaveAs(temp_path)
        wb.Close()
        excel.Quit()

        logging.info(f"SMTP cache saved successfully to {temp_path} via Excel COM.")

    except Exception as e:
        logging.error(f"Failed to save SMTP cache with label preservation: {e}")
        # Fallback to standard pandas save if Excel COM fails
        try:
            df.to_excel(self.smtp_cache_path, index=False)
            logging.warning("Saved via Pandas fallback (Labels likely stripped).")
        except:
            pass
    finally:
        pythoncom.CoUninitialize()